export const COUNTRIES = [
  { value: 'Argentina', label: 'Argentina' },
];

export const PROVINCES_BY_COUNTRY: Record<string, { value: string; label: string }[]> = {
  Argentina: [
    { value: 'Buenos Aires', label: 'Buenos Aires' },
    { value: 'CABA', label: 'Ciudad Autónoma de Buenos Aires' },
    { value: 'Catamarca', label: 'Catamarca' },
    { value: 'Chaco', label: 'Chaco' },
    { value: 'Chubut', label: 'Chubut' },
    { value: 'Córdoba', label: 'Córdoba' },
    { value: 'Corrientes', label: 'Corrientes' },
    { value: 'Entre Ríos', label: 'Entre Ríos' },
    { value: 'Formosa', label: 'Formosa' },
    { value: 'Jujuy', label: 'Jujuy' },
    { value: 'La Pampa', label: 'La Pampa' },
    { value: 'La Rioja', label: 'La Rioja' },
    { value: 'Mendoza', label: 'Mendoza' },
    { value: 'Misiones', label: 'Misiones' },
    { value: 'Neuquén', label: 'Neuquén' },
    { value: 'Río Negro', label: 'Río Negro' },
    { value: 'Salta', label: 'Salta' },
    { value: 'San Juan', label: 'San Juan' },
    { value: 'San Luis', label: 'San Luis' },
    { value: 'Santa Cruz', label: 'Santa Cruz' },
    { value: 'Santa Fe', label: 'Santa Fe' },
    { value: 'Santiago del Estero', label: 'Santiago del Estero' },
    { value: 'Tierra del Fuego', label: 'Tierra del Fuego' },
    { value: 'Tucumán', label: 'Tucumán' },
  ],
};

export const CITIES_BY_PROVINCE: Record<string, { value: string; label: string }[]> = {
  'Buenos Aires': [
    { value: 'La Plata', label: 'La Plata' },
    { value: 'Mar del Plata', label: 'Mar del Plata' },
    { value: 'Bahía Blanca', label: 'Bahía Blanca' },
    { value: 'Tandil', label: 'Tandil' },
    { value: 'San Nicolás', label: 'San Nicolás' },
    { value: 'Quilmes', label: 'Quilmes' },
    { value: 'Lanús', label: 'Lanús' },
    { value: 'Avellaneda', label: 'Avellaneda' },
    { value: 'Lomas de Zamora', label: 'Lomas de Zamora' },
    { value: 'Morón', label: 'Morón' },
    { value: 'San Isidro', label: 'San Isidro' },
    { value: 'Vicente López', label: 'Vicente López' },
    { value: 'Tigre', label: 'Tigre' },
    { value: 'Pilar', label: 'Pilar' },
    { value: 'Zárate', label: 'Zárate' },
    { value: 'Campana', label: 'Campana' },
    { value: 'Junín', label: 'Junín' },
    { value: 'Pergamino', label: 'Pergamino' },
    { value: 'Olavarría', label: 'Olavarría' },
    { value: 'Necochea', label: 'Necochea' },
  ],
  CABA: [
    { value: 'Palermo', label: 'Palermo' },
    { value: 'Recoleta', label: 'Recoleta' },
    { value: 'Belgrano', label: 'Belgrano' },
    { value: 'Caballito', label: 'Caballito' },
    { value: 'Villa Urquiza', label: 'Villa Urquiza' },
    { value: 'Flores', label: 'Flores' },
    { value: 'Almagro', label: 'Almagro' },
    { value: 'Villa Crespo', label: 'Villa Crespo' },
    { value: 'Núñez', label: 'Núñez' },
    { value: 'Colegiales', label: 'Colegiales' },
    { value: 'San Telmo', label: 'San Telmo' },
    { value: 'La Boca', label: 'La Boca' },
    { value: 'Puerto Madero', label: 'Puerto Madero' },
    { value: 'Monserrat', label: 'Monserrat' },
    { value: 'San Nicolás', label: 'San Nicolás' },
  ],
  Córdoba: [
    { value: 'Córdoba Capital', label: 'Córdoba Capital' },
    { value: 'Villa Carlos Paz', label: 'Villa Carlos Paz' },
    { value: 'Río Cuarto', label: 'Río Cuarto' },
    { value: 'Villa María', label: 'Villa María' },
    { value: 'San Francisco', label: 'San Francisco' },
    { value: 'Alta Gracia', label: 'Alta Gracia' },
    { value: 'Río Tercero', label: 'Río Tercero' },
    { value: 'La Falda', label: 'La Falda' },
    { value: 'Jesús María', label: 'Jesús María' },
    { value: 'Bell Ville', label: 'Bell Ville' },
  ],
  'Santa Fe': [
    { value: 'Rosario', label: 'Rosario' },
    { value: 'Santa Fe Capital', label: 'Santa Fe Capital' },
    { value: 'Rafaela', label: 'Rafaela' },
    { value: 'Venado Tuerto', label: 'Venado Tuerto' },
    { value: 'Reconquista', label: 'Reconquista' },
    { value: 'Villa Gobernador Gálvez', label: 'Villa Gobernador Gálvez' },
    { value: 'Casilda', label: 'Casilda' },
    { value: 'San Lorenzo', label: 'San Lorenzo' },
  ],
  Mendoza: [
    { value: 'Mendoza Capital', label: 'Mendoza Capital' },
    { value: 'San Rafael', label: 'San Rafael' },
    { value: 'Godoy Cruz', label: 'Godoy Cruz' },
    { value: 'Guaymallén', label: 'Guaymallén' },
    { value: 'Las Heras', label: 'Las Heras' },
    { value: 'Maipú', label: 'Maipú' },
    { value: 'Luján de Cuyo', label: 'Luján de Cuyo' },
    { value: 'Tunuyán', label: 'Tunuyán' },
  ],
  Tucumán: [
    { value: 'San Miguel de Tucumán', label: 'San Miguel de Tucumán' },
    { value: 'Yerba Buena', label: 'Yerba Buena' },
    { value: 'Tafí Viejo', label: 'Tafí Viejo' },
    { value: 'Banda del Río Salí', label: 'Banda del Río Salí' },
    { value: 'Concepción', label: 'Concepción' },
    { value: 'Monteros', label: 'Monteros' },
  ],
  Salta: [
    { value: 'Salta Capital', label: 'Salta Capital' },
    { value: 'San Ramón de la Nueva Orán', label: 'San Ramón de la Nueva Orán' },
    { value: 'Tartagal', label: 'Tartagal' },
    { value: 'General Güemes', label: 'General Güemes' },
    { value: 'Cafayate', label: 'Cafayate' },
  ],
  'Entre Ríos': [
    { value: 'Paraná', label: 'Paraná' },
    { value: 'Concordia', label: 'Concordia' },
    { value: 'Gualeguaychú', label: 'Gualeguaychú' },
    { value: 'Concepción del Uruguay', label: 'Concepción del Uruguay' },
    { value: 'Gualeguay', label: 'Gualeguay' },
    { value: 'Colón', label: 'Colón' },
  ],
  Misiones: [
    { value: 'Posadas', label: 'Posadas' },
    { value: 'Oberá', label: 'Oberá' },
    { value: 'Eldorado', label: 'Eldorado' },
    { value: 'Puerto Iguazú', label: 'Puerto Iguazú' },
    { value: 'Apóstoles', label: 'Apóstoles' },
  ],
  Corrientes: [
    { value: 'Corrientes Capital', label: 'Corrientes Capital' },
    { value: 'Goya', label: 'Goya' },
    { value: 'Mercedes', label: 'Mercedes' },
    { value: 'Curuzú Cuatiá', label: 'Curuzú Cuatiá' },
    { value: 'Paso de los Libres', label: 'Paso de los Libres' },
  ],
  Chaco: [
    { value: 'Resistencia', label: 'Resistencia' },
    { value: 'Presidencia Roque Sáenz Peña', label: 'Presidencia Roque Sáenz Peña' },
    { value: 'Villa Ángela', label: 'Villa Ángela' },
    { value: 'General San Martín', label: 'General San Martín' },
    { value: 'Charata', label: 'Charata' },
  ],
  'San Juan': [
    { value: 'San Juan Capital', label: 'San Juan Capital' },
    { value: 'Rawson', label: 'Rawson' },
    { value: 'Rivadavia', label: 'Rivadavia' },
    { value: 'Chimbas', label: 'Chimbas' },
    { value: 'Santa Lucía', label: 'Santa Lucía' },
  ],
  Jujuy: [
    { value: 'San Salvador de Jujuy', label: 'San Salvador de Jujuy' },
    { value: 'Palpalá', label: 'Palpalá' },
    { value: 'San Pedro', label: 'San Pedro' },
    { value: 'Libertador General San Martín', label: 'Libertador General San Martín' },
    { value: 'Tilcara', label: 'Tilcara' },
    { value: 'Humahuaca', label: 'Humahuaca' },
  ],
  'Río Negro': [
    { value: 'Viedma', label: 'Viedma' },
    { value: 'San Carlos de Bariloche', label: 'San Carlos de Bariloche' },
    { value: 'General Roca', label: 'General Roca' },
    { value: 'Cipolletti', label: 'Cipolletti' },
    { value: 'Allen', label: 'Allen' },
  ],
  Neuquén: [
    { value: 'Neuquén Capital', label: 'Neuquén Capital' },
    { value: 'San Martín de los Andes', label: 'San Martín de los Andes' },
    { value: 'Plottier', label: 'Plottier' },
    { value: 'Centenario', label: 'Centenario' },
    { value: 'Cutral Có', label: 'Cutral Có' },
    { value: 'Villa La Angostura', label: 'Villa La Angostura' },
  ],
  Chubut: [
    { value: 'Rawson', label: 'Rawson' },
    { value: 'Comodoro Rivadavia', label: 'Comodoro Rivadavia' },
    { value: 'Trelew', label: 'Trelew' },
    { value: 'Puerto Madryn', label: 'Puerto Madryn' },
    { value: 'Esquel', label: 'Esquel' },
  ],
  'San Luis': [
    { value: 'San Luis Capital', label: 'San Luis Capital' },
    { value: 'Villa Mercedes', label: 'Villa Mercedes' },
    { value: 'Merlo', label: 'Merlo' },
    { value: 'La Punta', label: 'La Punta' },
    { value: 'Justo Daract', label: 'Justo Daract' },
  ],
  Catamarca: [
    { value: 'San Fernando del Valle de Catamarca', label: 'San Fernando del Valle de Catamarca' },
    { value: 'Andalgalá', label: 'Andalgalá' },
    { value: 'Tinogasta', label: 'Tinogasta' },
    { value: 'Belén', label: 'Belén' },
  ],
  'La Rioja': [
    { value: 'La Rioja Capital', label: 'La Rioja Capital' },
    { value: 'Chilecito', label: 'Chilecito' },
    { value: 'Aimogasta', label: 'Aimogasta' },
    { value: 'Chamical', label: 'Chamical' },
  ],
  'La Pampa': [
    { value: 'Santa Rosa', label: 'Santa Rosa' },
    { value: 'General Pico', label: 'General Pico' },
    { value: 'Toay', label: 'Toay' },
    { value: 'General Acha', label: 'General Acha' },
  ],
  'Santiago del Estero': [
    { value: 'Santiago del Estero Capital', label: 'Santiago del Estero Capital' },
    { value: 'La Banda', label: 'La Banda' },
    { value: 'Termas de Río Hondo', label: 'Termas de Río Hondo' },
    { value: 'Añatuya', label: 'Añatuya' },
    { value: 'Frías', label: 'Frías' },
  ],
  Formosa: [
    { value: 'Formosa Capital', label: 'Formosa Capital' },
    { value: 'Clorinda', label: 'Clorinda' },
    { value: 'Pirané', label: 'Pirané' },
    { value: 'El Colorado', label: 'El Colorado' },
  ],
  'Santa Cruz': [
    { value: 'Río Gallegos', label: 'Río Gallegos' },
    { value: 'Caleta Olivia', label: 'Caleta Olivia' },
    { value: 'El Calafate', label: 'El Calafate' },
    { value: 'Pico Truncado', label: 'Pico Truncado' },
    { value: 'Puerto Deseado', label: 'Puerto Deseado' },
  ],
  'Tierra del Fuego': [
    { value: 'Ushuaia', label: 'Ushuaia' },
    { value: 'Río Grande', label: 'Río Grande' },
    { value: 'Tolhuin', label: 'Tolhuin' },
  ],
};
